CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  trx_id VARCHAR(64) NOT NULL,
  product_code VARCHAR(64) NOT NULL,
  target VARCHAR(128) NOT NULL,
  price INT NOT NULL DEFAULT 0,
  status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  message TEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_trx_id (trx_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
